
from datetime import datetime
created_date=input('ведите дату для создания заметки')
issue_date=input('ведите дату истечения срока заметки')
title=input('ведите заголовок вашей заметки')
created_date_obj=datetime.strptime(created_date," %d %m %Y")
issue_date_obj=datetime.strptime(issue_date," %d %m %Y")
morning=input('ведите время затрака')
lunch=input('ведите время обеда')
dinner=input('ведите время ужина')
morning_obj=datetime.strptime(morning," %H %M %S")
lunch_obj=datetime.strptime(lunch," %H %M %S")
dinner_obj=datetime.strptime(dinner," %H %M %S")
print(created_date_obj.day,issue_date_obj.day)
print(created_date_obj.day,issue_date_obj.month)
print('ваша заметка '+ title)
#print(morning_obj.hour,lunch_obj.hour,dinner_obj.hour)
#print(morning_obj.minute,lunch_obj.minute,dinner_obj.minute)
my_day=[title,morning,lunch,dinner]
print(my_day)
