username= input('ведите имя')
content=input('сделайте запись')
status=input('род дейтельности')
title=input('ведите заголовок вашей заметки')
created_date=input('ведите дату для создания заметки')
issue_date=input('ведите дату истечения срока заметки')
print(username)
print(content)
print(status)
print(title)
print(created_date)
print(issue_date)
